
CREATE DATABASE IF NOT EXISTS fertility;

USE fertility;

CREATE TABLE IF NOT EXISTS example(
    id int AUTO_INCREMENT, 
    country VARCHAR(50), 
    image VARCHAR(50),
    temperature INT, 
    temperature_rate INT, 
    temperature_intercept INT,
    rainfall INT, 
    rainfall_rate INT,
    rainfall_intercept INT,
    soil_type INT, 
    PRIMARY KEY(id)
);

INSERT INTO example ( country, image, temperature, temperature_rate, temperature_intercept, rainfall, rainfall_rate, rainfall_intercept, soil_type) VALUES 
    ("Japan", "japan.png", 20, 1.234, 1, 40, 3.143, 1, 2);


CREATE TABLE IF NOT EXISTS temp(
   Country     VARCHAR(29) NOT NULL PRIMARY KEY,
  Temperature NUMERIC(6,2) NOT NULL
);
INSERT INTO temp (Country,Temperature) VALUES ('Burkina Faso',29.28);
INSERT INTO temp(Country,Temperature) VALUES ('Mali',29.19);
INSERT INTO temp(Country,Temperature) VALUES ('Qatar',29.11);
INSERT INTO temp(Country,Temperature) VALUES ('Senegal',29);
INSERT INTO temp(Country,Temperature) VALUES ('United Arab Emirates',28.93);
INSERT INTO temp(Country,Temperature) VALUES ('Mauritania',28.9);
INSERT INTO temp(Country,Temperature) VALUES ('Bahrain',28.84);
INSERT INTO temp(Country,Temperature) VALUES ('Aruba',28.82);
INSERT INTO temp(Country,Temperature) VALUES ('Djibouti',28.6);
INSERT INTO temp(Country,Temperature) VALUES ('Gambia',28.46);
INSERT INTO temp(Country,Temperature) VALUES ('Benin',28.09);
INSERT INTO temp(Country,Temperature) VALUES ('Maldives',28.08);
INSERT INTO temp(Country,Temperature) VALUES ('Guinea Bissau',28.05);
INSERT INTO temp(Country,Temperature) VALUES ('Cayman Islands',28.01);
INSERT INTO temp(Country,Temperature) VALUES ('Oman',27.94);
INSERT INTO temp(Country,Temperature) VALUES ('Marshall Islands',27.9);
INSERT INTO temp(Country,Temperature) VALUES ('Kiribati',27.77);
INSERT INTO temp(Country,Temperature) VALUES ('Ghana',27.73);
INSERT INTO temp(Country,Temperature) VALUES ('Singapore',27.7);
INSERT INTO temp(Country,Temperature) VALUES ('Niger',27.61);
INSERT INTO temp(Country,Temperature) VALUES ('Kuwait',27.58);
INSERT INTO temp(Country,Temperature) VALUES ('Sudan',27.57);
INSERT INTO temp(Country,Temperature) VALUES ('Guam',27.54);
INSERT INTO temp(Country,Temperature) VALUES ('Palau',27.54);
INSERT INTO temp(Country,Temperature) VALUES ('Samoa',27.53);
INSERT INTO temp(Country,Temperature) VALUES ('Togo',27.47);
INSERT INTO temp(Country,Temperature) VALUES ('Micronesia',27.45);
INSERT INTO temp(Country,Temperature) VALUES ('St Kitts and Nevis',27.34);
INSERT INTO temp(Country,Temperature) VALUES ('American Samoa',27.31);
INSERT INTO temp(Country,Temperature) VALUES ('Chad',27.28);
INSERT INTO temp(Country,Temperature) VALUES ('Cambodia',27.25);
INSERT INTO temp(Country,Temperature) VALUES ('Northern Mariana Islands',27.25);
INSERT INTO temp(Country,Temperature) VALUES ('Sri Lanka',27.24);
INSERT INTO temp(Country,Temperature) VALUES ('Nigeria',27.15);
INSERT INTO temp(Country,Temperature) VALUES ('Seychelles',27.11);
INSERT INTO temp(Country,Temperature) VALUES ('Somalia',27.1);
INSERT INTO temp(Country,Temperature) VALUES ('Antigua and Barbuda',27.06);
INSERT INTO temp(Country,Temperature) VALUES ('Ivory Coast',26.84);
INSERT INTO temp(Country,Temperature) VALUES ('Virgin Islands',26.84);
INSERT INTO temp(Country,Temperature) VALUES ('St Lucia',26.83);
INSERT INTO temp(Country,Temperature) VALUES ('Thailand',26.78);
INSERT INTO temp(Country,Temperature) VALUES ('Dominica',26.68);
INSERT INTO temp(Country,Temperature) VALUES ('Sierra Leone',26.64);
INSERT INTO temp(Country,Temperature) VALUES ('Philippines',26.61);
INSERT INTO temp(Country,Temperature) VALUES ('Suriname',26.53);
INSERT INTO temp(Country,Temperature) VALUES ('Eritrea',26.49);
INSERT INTO temp(Country,Temperature) VALUES ('Saudi Arabia',26.46);
INSERT INTO temp(Country,Temperature) VALUES ('Trinidad and Tobago',26.46);
INSERT INTO temp(Country,Temperature) VALUES ('Barbados',26.45);
INSERT INTO temp(Country,Temperature) VALUES ('Malaysia',26.35);
INSERT INTO temp(Country,Temperature) VALUES ('Grenada',26.33);
INSERT INTO temp(Country,Temperature) VALUES ('Guyana',26.16);
INSERT INTO temp(Country,Temperature) VALUES ('Cuba',26.14);
INSERT INTO temp(Country,Temperature) VALUES ('Bahamas',26.05);
INSERT INTO temp(Country,Temperature) VALUES ('Jamaica',26.02);
INSERT INTO temp(Country,Temperature) VALUES ('St Vincent and the Grenadines',25.98);
INSERT INTO temp(Country,Temperature) VALUES ('Indonesia',25.96);
INSERT INTO temp(Country,Temperature) VALUES ('Guinea',25.95);
INSERT INTO temp(Country,Temperature) VALUES ('Solomon Islands',25.89);
INSERT INTO temp(Country,Temperature) VALUES ('Belize',25.83);
INSERT INTO temp(Country,Temperature) VALUES ('Nicaragua',25.81);
INSERT INTO temp(Country,Temperature) VALUES ('Bangladesh',25.74);
INSERT INTO temp(Country,Temperature) VALUES ('Central African Republic',25.56);
INSERT INTO temp(Country,Temperature) VALUES ('Brazil',25.54);
INSERT INTO temp(Country,Temperature) VALUES ('Venezuela',25.52);
INSERT INTO temp(Country,Temperature) VALUES ('Yemen',25.51);
INSERT INTO temp(Country,Temperature) VALUES ('Liberia',25.47);
INSERT INTO temp(Country,Temperature) VALUES ('Gabon',25.46);
INSERT INTO temp(Country,Temperature) VALUES ('Panama',25.33);
INSERT INTO temp(Country,Temperature) VALUES ('El Salvador',25.23);
INSERT INTO temp(Country,Temperature) VALUES ('Kenya',25.22);
INSERT INTO temp(Country,Temperature) VALUES ('India',25.2);
INSERT INTO temp(Country,Temperature) VALUES ('Tonga',25.1);
INSERT INTO temp(Country,Temperature) VALUES ('Republic of the Congo',25.05);
INSERT INTO temp(Country,Temperature) VALUES ('Haiti',25.01);
INSERT INTO temp(Country,Temperature) VALUES ('Fiji',24.98);
INSERT INTO temp(Country,Temperature) VALUES ('Cameroon',24.94);
INSERT INTO temp(Country,Temperature) VALUES ('Puerto Rico',24.94);
INSERT INTO temp(Country,Temperature) VALUES ('Equatorial Guinea',24.89);
INSERT INTO temp(Country,Temperature) VALUES ('Mayotte',24.87);
INSERT INTO temp(Country,Temperature) VALUES ('Papua New Guinea',24.78);
INSERT INTO temp(Country,Temperature) VALUES ('Vanuatu',24.76);
INSERT INTO temp(Country,Temperature) VALUES ('Vietnam',24.73);
INSERT INTO temp(Country,Temperature) VALUES ('Colombia',24.71);
INSERT INTO temp(Country,Temperature) VALUES ('Honduras',24.71);
INSERT INTO temp(Country,Temperature) VALUES ('Sao Tome and Principe',24.66);
INSERT INTO temp(Country,Temperature) VALUES ('Costa Rica',24.64);
INSERT INTO temp(Country,Temperature) VALUES ('Dominican Republic',24.57);
INSERT INTO temp(Country,Temperature) VALUES ('Mozambique',24.42);
INSERT INTO temp(Country,Temperature) VALUES ('Congo',24.38);
INSERT INTO temp(Country,Temperature) VALUES ('Algeria',24.11);
INSERT INTO temp(Country,Temperature) VALUES ('French Polynesia',24.05);
INSERT INTO temp(Country,Temperature) VALUES ('Laos',24.05);
INSERT INTO temp(Country,Temperature) VALUES ('Myanmar',23.96);
INSERT INTO temp(Country,Temperature) VALUES ('Paraguay',23.86);
INSERT INTO temp(Country,Temperature) VALUES ('Iraq',23.81);
INSERT INTO temp(Country,Temperature) VALUES ('Guatemala',23.77);
INSERT INTO temp(Country,Temperature) VALUES ('Comoros',23.74);
INSERT INTO temp(Country,Temperature) VALUES ('Hong Kong',23.62);
INSERT INTO temp(Country,Temperature) VALUES ('Ethiopia',23.45);
INSERT INTO temp(Country,Temperature) VALUES ('Macau',23.4);
INSERT INTO temp(Country,Temperature) VALUES ('New Caledonia',23.37);
INSERT INTO temp(Country,Temperature) VALUES ('Mauritius',23.27);
INSERT INTO temp(Country,Temperature) VALUES ('Egypt',23.23);
INSERT INTO temp(Country,Temperature) VALUES ('Uganda',23.14);
INSERT INTO temp(Country,Temperature) VALUES ('Tanzania',22.9);
INSERT INTO temp(Country,Temperature) VALUES ('Libya',22.8);
INSERT INTO temp(Country,Temperature) VALUES ('Madagascar',22.7);
INSERT INTO temp(Country,Temperature) VALUES ('Cape Verde',22.67);
INSERT INTO temp(Country,Temperature) VALUES ('Malawi',22.55);
INSERT INTO temp(Country,Temperature) VALUES ('Pakistan',22.23);
INSERT INTO temp(Country,Temperature) VALUES ('Botswana',22);
INSERT INTO temp(Country,Temperature) VALUES ('Australia',21.96);
INSERT INTO temp(Country,Temperature) VALUES ('Zambia',21.92);
INSERT INTO temp(Country,Temperature) VALUES ('Zimbabwe',21.83);
INSERT INTO temp(Country,Temperature) VALUES ('Mexico',21.7);
INSERT INTO temp(Country,Temperature) VALUES ('Angola',21.63);
INSERT INTO temp(Country,Temperature) VALUES ('Tunisia',21.44);
INSERT INTO temp(Country,Temperature) VALUES ('Ecuador',21.07);
INSERT INTO temp(Country,Temperature) VALUES ('Swaziland',20.92);
INSERT INTO temp(Country,Temperature) VALUES ('Taiwan',20.79);
INSERT INTO temp(Country,Temperature) VALUES ('Bolivia',20.68);
INSERT INTO temp(Country,Temperature) VALUES ('Burundi',20.43);
INSERT INTO temp(Country,Temperature) VALUES ('Malta',20.26);
INSERT INTO temp(Country,Temperature) VALUES ('Namibia',20.24);
INSERT INTO temp(Country,Temperature) VALUES ('Israel',20.23);
INSERT INTO temp(Country,Temperature) VALUES ('Jordan',19.77);
INSERT INTO temp(Country,Temperature) VALUES ('Palestine',19.7);
INSERT INTO temp(Country,Temperature) VALUES ('Peru',19.58);
INSERT INTO temp(Country,Temperature) VALUES ('Cyprus',19.33);
INSERT INTO temp(Country,Temperature) VALUES ('Iran',19.3);
INSERT INTO temp(Country,Temperature) VALUES ('Syria',19.17);
INSERT INTO temp(Country,Temperature) VALUES ('Rwanda',19.14);
INSERT INTO temp(Country,Temperature) VALUES ('Morocco',19.1);
INSERT INTO temp(Country,Temperature) VALUES ('South Africa',18.42);
INSERT INTO temp(Country,Temperature) VALUES ('Uruguay',17.73);
INSERT INTO temp(Country,Temperature) VALUES ('Turkmenistan',17.66);
INSERT INTO temp(Country,Temperature) VALUES ('Portugal',16.9);
INSERT INTO temp(Country,Temperature) VALUES ('Lebanon',15.66);
INSERT INTO temp(Country,Temperature) VALUES ('Spain',15.3);
INSERT INTO temp(Country,Temperature) VALUES ('Argentina',15.07);
INSERT INTO temp(Country,Temperature) VALUES ('Monaco',15.01);
INSERT INTO temp(Country,Temperature) VALUES ('Greece',14.88);
INSERT INTO temp(Country,Temperature) VALUES ('Uzbekistan',14.86);
INSERT INTO temp(Country,Temperature) VALUES ('Afghanistan',14.48);
INSERT INTO temp(Country,Temperature) VALUES ('Nepal',14.39);
INSERT INTO temp(Country,Temperature) VALUES ('Italy',14.38);
INSERT INTO temp(Country,Temperature) VALUES ('San Marino',14.14);
INSERT INTO temp(Country,Temperature) VALUES ('Azerbaijan',13.84);
INSERT INTO temp(Country,Temperature) VALUES ('Albania',13.31);
INSERT INTO temp(Country,Temperature) VALUES ('Croatia',13.16);
INSERT INTO temp(Country,Temperature) VALUES ('France',13.16);
INSERT INTO temp(Country,Temperature) VALUES ('South Korea',12.76);
INSERT INTO temp(Country,Temperature) VALUES ('Lesotho',12.64);
INSERT INTO temp(Country,Temperature) VALUES ('Hungary',12.62);
INSERT INTO temp(Country,Temperature) VALUES ('Serbia',12.56);
INSERT INTO temp(Country,Temperature) VALUES ('Japan',12.42);
INSERT INTO temp(Country,Temperature) VALUES ('Bulgaria',12.28);
INSERT INTO temp(Country,Temperature) VALUES ('Turkey',12.24);
INSERT INTO temp(Country,Temperature) VALUES ('Belgium',11.98);
INSERT INTO temp(Country,Temperature) VALUES ('Moldova',11.9);
INSERT INTO temp(Country,Temperature) VALUES ('Netherlands',11.72);
INSERT INTO temp(Country,Temperature) VALUES ('Macedonia',11.66);
INSERT INTO temp(Country,Temperature) VALUES ('New Zealand',11.66);
INSERT INTO temp(Country,Temperature) VALUES ('Bosnia and Herzegovina',11.57);
INSERT INTO temp(Country,Temperature) VALUES ('Luxembourg',11.43);
INSERT INTO temp(Country,Temperature) VALUES ('Romania',11.2);
INSERT INTO temp(Country,Temperature) VALUES ('Slovenia',11.04);
INSERT INTO temp(Country,Temperature) VALUES ('Montenegro',11);
INSERT INTO temp(Country,Temperature) VALUES ('Germany',10.83);
INSERT INTO temp(Country,Temperature) VALUES ('Bhutan',10.56);
INSERT INTO temp(Country,Temperature) VALUES ('Ireland',10.35);
INSERT INTO temp(Country,Temperature) VALUES ('United Kingdom',10.11);
INSERT INTO temp(Country,Temperature) VALUES ('Ukraine',10.04);
INSERT INTO temp(Country,Temperature) VALUES ('Georgia',9.92);
INSERT INTO temp(Country,Temperature) VALUES ('Isle of Man',9.89);
INSERT INTO temp(Country,Temperature) VALUES ('Slovakia',9.81);
INSERT INTO temp(Country,Temperature) VALUES ('Denmark',9.77);
INSERT INTO temp(Country,Temperature) VALUES ('Andorra',9.73);
INSERT INTO temp(Country,Temperature) VALUES ('United States',9.73);
INSERT INTO temp(Country,Temperature) VALUES ('Czech Republic',9.71);
INSERT INTO temp(Country,Temperature) VALUES ('Poland',9.7);
INSERT INTO temp(Country,Temperature) VALUES ('Chile',9.37);
INSERT INTO temp(Country,Temperature) VALUES ('Liechtenstein',9.05);
INSERT INTO temp(Country,Temperature) VALUES ('Austria',8.65);
INSERT INTO temp(Country,Temperature) VALUES ('Armenia',8.64);
INSERT INTO temp(Country,Temperature) VALUES ('China',8.1);
INSERT INTO temp(Country,Temperature) VALUES ('Switzerland',8.08);
INSERT INTO temp(Country,Temperature) VALUES ('Kazakhstan',8.06);
INSERT INTO temp(Country,Temperature) VALUES ('Belarus',7.98);
INSERT INTO temp(Country,Temperature) VALUES ('Lithuania',7.95);
INSERT INTO temp(Country,Temperature) VALUES ('North Korea',7.46);
INSERT INTO temp(Country,Temperature) VALUES ('Latvia',7.4);
INSERT INTO temp(Country,Temperature) VALUES ('Faroe Islands',7.1);
INSERT INTO temp(Country,Temperature) VALUES ('Estonia',6.9);
INSERT INTO temp(Country,Temperature) VALUES ('Tajikistan',5.09);
INSERT INTO temp(Country,Temperature) VALUES ('Kyrgyzstan',3.93);
INSERT INTO temp(Country,Temperature) VALUES ('Sweden',3.84);
INSERT INTO temp(Country,Temperature) VALUES ('Finland',3.24);
INSERT INTO temp(Country,Temperature) VALUES ('Norway',2.88);
INSERT INTO temp(Country,Temperature) VALUES ('Iceland',2.11);
INSERT INTO temp(Country,Temperature) VALUES ('Mongolia',1.31);
INSERT INTO temp(Country,Temperature) VALUES ('Russia',-2.87);
INSERT INTO temp(Country,Temperature) VALUES ('Canada',-4.22);
INSERT INTO temp(Country,Temperature) VALUES ('Greenland',-18.62);


CREATE TABLE IF NOT EXISTS CRI_table(
  Country     VARCHAR(36) NOT NULL PRIMARY KEY
  ,Normalize   VARCHAR(11) NOT NULL
);
INSERT INTO CRI_table(Country,Normalize) VALUES ('Albania','0.857740586');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Algeria','0.73916318');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Angola','0.589958159');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Antigua and Barbuda','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Argentina','0.358410042');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Armenia','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Australia','0.368200837');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Austria','0.422594142');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Azerbaijan','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Bahrain','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Bangladesh','0.669456067');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Barbados','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Belarus','0.889790795');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Belgium','0.63874477');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Belize','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Benin','0.690376569');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Bhutan','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Bolivia','0.485355649');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Bosnia and Herzegovina','0.871715481');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Botswana','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Brazil','0.647112971');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Brunei Darussalam','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Bulgaria','0.79916318');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Burkina Faso','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Burundi','0.257991632');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Cambodia','0.352887029');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Cameroon','0.83958159');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Canada','0.13665272');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Cape Verde','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Central African Republic','0.549539749');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Chad','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Chile','0.633221757');
INSERT INTO CRI_table(Country,Normalize) VALUES ('China','0.331966527');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Chinese Taipei','0.559246862');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Colombia','0.464435146');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Comoros','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Costa Rica','0.66251046');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Côte d''Ivoire','0.70292887');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Croatia','0.860502092');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Cyprus','0.569037657');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Czech Republic','0.345857741');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Democratic Republic of Congo','0.53832636');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Democratic Republic of Ti-
mor-Leste','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Denmark','0.467196653');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Djibouti','0.327782427');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Dominica','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Dominican Republic','0.677824268');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Ecuador','0.765690377');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Egypt','0.905188285');
INSERT INTO CRI_table(Country,Normalize) VALUES ('El Salvador','0.324937238');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Eritrea','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Estonia','0.711297071');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Eswatini','0.76292887');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Ethiopia','0.479748954');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Fiji','0.142259414');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Finland','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('France','0.340334728');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Gabon','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Georgia','0.772635983');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Germany','0.069707113');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Ghana','0.525774059');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Greece','0.152050209');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Grenada','0.543933054');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Guatemala','0.601087866');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Guinea','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Guinea-Bissau','0.351464435');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Guyana','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Haiti','0.695983264');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Honduras','0.386359833');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Hungary','0.850794979');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Iceland','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('India','0.106025105');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Indonesia','0.524435146');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Iraq','0.527196653');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Ireland','0.594142259');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Islamic Republic of Afghani-
stan','0.255230126');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Islamic Republic of Iran','0.496485356');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Israel','0.70292887');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Italy','0.235732218');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Jamaica','0.870292887');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Japan','0');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Jordan','0.396731969');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Kazakhstan','0.767196697');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Kenya','0.074672758');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Kiribati','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Korea, Republic of','0.57392603');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Kosovo','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Kuwait','0.453834666');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Kyrgyz Republic','0.934112273');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Lao People''s Democratic Re-
public','0.213739787');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Latvia','0.341122727');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Lebanon','0.491961697');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Lesotho','0.442150575');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Liberia','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Libya','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Lithuania','0.15953615');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Luxembourg','0.642712817');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Madagascar','0.040938241');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Malawi','0.636914697');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Malaysia','0.647105333');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Maldives','0.809628393');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Mali','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Malta','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Marshall Islands','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Mauritania','0.789159273');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Mauritius','0.594395151');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Mexico','0.232803303');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Micronesia','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Moldova','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Mongolia','0.13616797');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Montenegro','0.764297637');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Morocco','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Mozambique','0.439251515');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Myanmar','0.374769393');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Namibia','0.597382061');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Nepal','0.162523061');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Netherlands','0.491961697');
INSERT INTO CRI_table(Country,Normalize) VALUES ('New Zealand','0.368971273');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Nicaragua','0.430466485');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Niger','0.250373364');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Nigeria','0.155143635');
INSERT INTO CRI_table(Country,Normalize) VALUES ('North Macedonia','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Norway','0.639813757');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Oman','0.115610999');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Pakistan','0.673460423');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Panama','0.633927787');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Papua New Guinea','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Paraguay','0.862338575');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Peru','0.72766406');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Philippines','0');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Poland','0.283018868');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Portugal','0.48745283');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Puerto Rico','0.836509434');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Qatar','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Republic of Congo','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Republic of Yemen','0.210660377');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Romania','0.591226415');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Russia','0.533018868');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Rwanda','0.020471698');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Samoa','0.485849057');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Saudi Arabia','0.655660377');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Senegal','0.806603774');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Serbia','0.438679245');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Seychelles','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Sierra Leone','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Singapore','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Slovak Republic','0.654056604');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Slovenia','0.366320755');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Solomon Islands','0.228018868');
INSERT INTO CRI_table(Country,Normalize) VALUES ('South Africa','0.323867925');
INSERT INTO CRI_table(Country,Normalize) VALUES ('South Sudan','0.91509434');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Spain','0.270471698');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Sri Lanka','0');
INSERT INTO CRI_table(Country,Normalize) VALUES ('St. Kitts and Nevis','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('St. Lucia','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('St. Vincent and the Grena-
dines','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Sudan','0.252051003');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Suriname','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Sweden','0.64416329');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Switzerland','0.492636157');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Tajikistan','0.467925274');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Tanzania','0.454680241');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Thailand','0.444795888');
INSERT INTO CRI_table(Country,Normalize) VALUES ('The Bahamas','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('The Gambia','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Togo','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Tonga','0.013245033');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Trinidad and Tobago','0.568350301');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Tunisia','0.227340121');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Turkey','0.547000099');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Tuvalu','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Uganda','0.008302857');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Ukraine','0.805574775');
INSERT INTO CRI_table(Country,Normalize) VALUES ('United Arab Emirates','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('United Kingdom','0.494217653');
INSERT INTO CRI_table(Country,Normalize) VALUES ('United States','0');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Uruguay','0.096124659');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Uzbekistan','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Vanuatu','0.187190124');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Venezuela','0.789234038');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Vietnam','0');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Zambia','1');
INSERT INTO CRI_table(Country,Normalize) VALUES ('Zimbabwe','0');
